version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-data-agent
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_intelligence
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent_user -d sales_intelligence"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data_agents_network

  chroma:
    image: chromadb/chroma:0.4.15
    container_name: chroma-vector-db
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=False
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - data_agents_network

volumes:
  postgres_data:
    driver: local
  chroma_data:
    driver: local

networks:
  data_agents_network:
    driver: bridge
